events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://quine:8080;

      add_header Access-Control-Allow-Origin "*";
      add_header Access-Control-Allow-Methods "GET, OPTIONS";
      add_header Access-Control-Allow-Headers "Content-Type, Authorization";

      if ($request_method = OPTIONS) {
        return 204;
      }
    }
  }
}
